import random
kelimeler = ["GÖZƏL ","BİLİK","PROBLEM","TƏMİN","AYRILMAQ","ZAMAN","SUSAMAQ","EDİN","İSTİFADƏ","YOX","BAX",
              "AXTARMAQ", "DOVŞAN", "AMMA", "MANAT", "OYNAMAQ", "ÇİÇƏK", "ŞƏHƏR", "YÜKSƏK", "DÖYÜŞ", "VARLIQ", "GÜVƏNMƏK",
              "GÜVƏN", "LAZIM", "MÜALİCƏ", "ŞƏHİD", "RAHAT", "SOYUQ", "ORADAN", "KİTAB", "PAYIZ", "HESAB", "BƏDƏN",
              'ZƏMİN', 'DƏMİZ', 'SİSTEM', 'GÖZLƏMƏK', 'ÇƏKİNMƏK', 'TEXNİKA', 'YAŞLANMAQ', 'GƏTİRMƏK', 'TARİX', 'DƏQİQ', 'BAŞLIQ',
              "CƏRİMƏ", "ƏGƏR", "ANCAQ", "QAYTARMAQ", "VERMƏK", "VAR", "QALIQ", "ŞƏXS", "BAŞQA", "DÖVR", "YENİDƏN", "BUNLAR",
              "KİTAB", "HADİSƏ", "OLMAQ", "MÜBARİZƏ", "DÖVLƏT", "ÖDƏMƏK", "DƏYİŞMƏK", "BAXMAQ", "DİVAN", "BELƏ", "BƏZİ", "BAŞLAMAQ",
              "SAXLA", "PƏRDƏ", "BİRİ", "ETDİRMƏK", "SU", "BƏYƏN", "BƏLƏDİYYƏ", "SAĞOL", "ORTA", "DƏYƏRSİZ", "BÖYÜTMƏK", "ETMƏK",
              "YENİ", "ƏSƏB", "SORUŞMAQ", "DÖYÜŞMƏK", "YANDIRMAQ", 'EŞİTMƏK', 'İKİSİ', "HƏMİŞƏ", "SƏSLİ", "İNANMAQ", "YOXLAMAQ", "SAAT", "NECƏ",
              'BİR', 'VƏ', 'OLMAQ', 'BU', 'ÜÇÜN', 'NƏFƏS', 'MƏN', 'DEMƏK', 'İNƏK', 'VƏTƏN', 'NƏSİL', 'BƏYƏNMƏK', 'DÖYMƏK', 'ALMAQ',
              'DƏYƏRLİ', 'ÖZ', 'GÜIMƏK', 'BİRLİKDƏ', 'VERMƏK', 'AMMA', 'SONRA', 'QƏDƏR', 'YER', 'ÇOXLUQ', 'İNSANLAR', 'BİZİM', 'HƏR ', 'İSTƏMƏK', 'İL', 'ÇIXMAQ', 'GÖRMƏK', 'GÜN', 'BİZ', 'GETMƏK', 'İŞLƏMƏK', 'ŞEY', 'OXŞAMAQ', 'BİLMƏK', 'SƏNƏTKAR', 'ZAMAN',
              'DİNLƏMƏK', 'UŞAQ', 'İKİ', 'DÖZMƏK', 'BİRLİK', 'SƏBR', 'BÖYÜK', 'SEVİLMƏK', 'BAŞLANĞIC', 'YOL', 'QAL', 'NİYƏ', 'SƏN',
              'MÖVZU', 'İBARƏT', 'YAXŞI', 'QADIN', 'EV', 'OLMAQ', 'QEYRƏT', 'DEMƏK', 'GÖZ', 'LAZIM', 'DÜNYA',
              "YEMƏK', 'HEÇ', 'HƏTTA', 'NECƏ', 'HAMISI', 'ƏLEYHİNƏ', 'TAPMAQ', 'BELƏ', 'YAŞAMAQ', 'DÜŞÜNMƏK', 'EYNİ', 'İÇMƏK', 'LAKİN",
              'İMAN', 'ONLAR', 'BİRİNCİ', 'GÖRƏ', 'ÖLMƏK', 'SON', 'BƏHANƏ', 'FORMA', 'VACİB', 'ÜZ', 'FUTBOI', 'GÖSTƏRMƏK', 'ETMƏK',
              'ALMA', 'GÜNAH', 'İSTİFADƏ', 'ÇÜNKÜ', 'YAN', 'İNDİ', 'KİŞİ', 'ONUN', 'BAŞQASI', 'XƏYANƏT', 'BAĞIŞLAMAQ', 'OĞUR', 'HƏMİŞƏIİK',
              'SAĞ', 'DURMAQ', 'QIZ', 'HAMISI', 'CƏLB', 'GÖSTƏRİŞ', 'DANIŞMAQ', 'PUL', 'ANLAMAQ', 'ANA', 'İLAN', 'BƏZİ', 'ATA', 'HƏYAT ',
              'YALNIZ', 'KİÇİK', 'DAHA', 'MƏLUMAT', 'KEÇİRMƏK', 'SORUŞ', 'HƏDİYYƏ', 'SÖYLƏMƏK', 'YENİDƏN', 'TƏMİN', 'NƏTİCƏ', 'İSTİFADƏ', 'XARİCİ ',
              'KİMSƏ', 'ORDAN', 'MÜDDƏT', 'DÖNDƏRMƏK', 'YANMAQ', 'OTURMAQ', 'DEMƏK', 'ÇIXMAQ', 'DƏRHAL', 'VAXT', 'QRUZ', 'PROBLEM', 'DİL',
              'HƏKİM', 'SƏTİR', 'YAZMAQ', 'FAİZ', 'AYLIQ', 'ATMAQ', 'TUTMAQ', 'QAYDALAR', 'HADİSƏ', 'DÜŞMƏK', 'EŞİTMƏK', 'SÖZÜ', 'GÖZƏL',
              'SEVMƏK', 'BİR', 'ÇƏTİN', 'ALMAQ', 'İTİRMƏK', 'QOYMAQ', 'BİR', 'KİMSƏ', 'BİRLİKDƏ', 'VERİLƏCƏK', 'KİM', 'BAYRAQ', 'GƏNC',
              'QAPI', 'KİTAB', 'QEYRƏTLİ', 'BURADA', 'GECƏ', 'ALAN', 'DİVAR', 'MEYDAN', 'GÖZLƏYİN', 'UZUN', 'QIŞ', 'GÜNƏŞ', 'AXIRINCI',
              'KİMSƏ', 'MƏHSUL', 'AİLƏ', 'KİMSƏSİZ', 'OXUMAQ', 'KİŞİ', 'HAMI', 'GÜC', 'BƏLKƏ', 'REAL', 'TAM', 'ƏLAQƏLİ', 'MÜNASİBƏT ',
              'MÜHİT', 'KÖHNƏ', 'AXTARIŞ', 'TƏBİB', 'OĞLU', 'YAXINLIQ', 'KÜÇƏ', 'TARİX', 'MÜLKİYYƏT', 'BÖLMƏ', 'ÖZƏL', 'SƏBƏBSİZ',
              'HEÇ', 'KİM', 'ÇOX', 'DEYİL', 'ƏGəR', 'LAZIMSIZ', 'XÜSUSİ', 'MƏNA', 'YÜKSƏLƏ', 'BANK', 'TƏRBİYƏ', 'DƏFƏ', 'AYAQ', 'HƏRƏKƏT', 'GERİ', 'CƏMİYYƏT',
              'ALƏT', 'GİTARA', 'NÖV', 'QƏRAR', 'İNTERNET', 'HAVA', 'NÖMRƏ', 'FƏRQLİ', 'QRUP', 'OTAQ', 'TOPLUQ', 'XƏBƏR', 'XƏBƏRLƏR',
              'ALLAH', 'HƏMÇİNİ', 'GƏLƏN', 'ŞEYTAN', 'SUAL', 'GERİ', 'QAZANMAQ', 'POST', 'MƏKTƏB', 'AÇIQ', 'ÖYRƏN', 'SÜRÜŞ',
              'DİL', 'ŞİRKƏT', 'MƏNBƏ', 'BİTİR', 'PROQRAM', 'DAVAM', 'HƏRƏKƏT', 'RƏNG', 'AÇMAQ', 'SAĞ', 'İNAN',
              'TƏHSİL', 'BUCAQ', 'PARÇA', 'QƏZET', 'TƏRİFLƏMƏK', 'ƏLBƏT', 'DƏYƏR', 'BİLMƏK', 'BƏRBƏR', 'DOKTOR', 'GƏLİR',
              'TAPŞIRIQ', 'MƏQSƏD', 'REGİON', 'FİLM', 'İŞTİRAK', 'MÜŞTƏRİ', 'ARTIQ', 'TELEFON', 'TƏHSİL', 'DƏNİZ', 'İKİNCİ',
              'QALX', 'HƏTTA', 'TƏSİR', 'İNKİŞAF', 'KEÇMƏK', 'BƏDƏN', 'DÜŞÜNCƏ', 'MİLYON', 'OYNAMAQ', 'DƏYİŞİKLİK', 'ƏSAS',
              'YARATMAQ', 'ÇATMAQ', 'DÜŞÜNMƏK', 'KEÇMƏK', 'MƏDƏNİYYƏT', 'QURMAQ', 'AMMA', 'BUNA', 'RƏSMİ', 'ETMƏK', 'İŞIQLANDIRMAQ', 'İÇMƏK',
              'XANIM', 'XİDMƏT', 'EHTİYAC', 'NÖQTƏ', 'İSTİQAMƏT', 'BƏLİ', 'OYUN', 'ARTIRMA', 'TƏKRAR', 'PROSES', 'QISA', 'ASAN',
              'HANSI', 'QİYMƏT', 'ƏSLİNDƏ', 'QƏBUL', 'EDİRƏM', 'ORADA', 'DİQQƏT', 'UZAQ', 'KOMPÜTER', 'GƏLƏCƏK', 'GÖRÜNÜR',
              'MƏSƏLƏN', 'OĞUL', 'DİNLƏMƏ', 'UYĞUN', 'LİRƏ', 'İSTEHSAL', 'DƏQİQƏ', 'UNUTMAQ', 'GƏZİNTİ', 'BELƏ', 'PİS',
              'AVTOMOBİL', 'AĞIZ', 'HİSS', 'TƏTBİQ', 'HƏLƏ', 'NÜMUNƏ', 'İŞIQ', 'BAXMAQ', 'DƏRƏCƏ', 'MÜMKÜN', 'BELƏ',
              'DİVAR', 'ONUN', 'İNCƏSƏNƏT', 'HAQDA', 'XƏSTƏLİK', 'TƏLƏBƏ', 'TELEVİZİYA', 'METOD', 'MASA', 'ÖLÜM', 'KOMANDA', 'TOP',
              'BAŞ', 'MUSİQİ', 'AYRILMAQ', 'ENERJİ', 'UNİVERSİTET', 'İDMAN', 'MEHRİBAN', 'RUH', 'BAXMAYARAQ', 'HİSSƏ', 'ÖLÜM',
              'DAİMİ', 'SAĞLAMLIQ', 'MÜXTƏLİF', 'BUNDAN', 'HİSS', 'HALBUKİ', 'SƏHƏR', 'İNTERNET', 'TEXNİKİ', 'ÇIXIŞ',
              'MƏRKƏZ', 'EKOLOGİYA', 'ƏVƏZİNDƏ', 'SƏVİYYƏ', 'KƏND', 'İDARƏETMƏ', 'AŞAĞI', 'CAVAB', 'LAY', 'TORPAQ', 'AXŞAM', 'ARAŞDIRMA', 'GÖTÜRMƏK', 'İŞTİRAK', 'ETMƏK', 'ƏKS', 'QURMAQ', 'ÖDƏMƏK', 'SANKİ', 'QAN', 'XƏSTƏ', 'ŞƏHƏR', 'ENMƏK',
              'İNDİKİ', 'MƏLUM', 'HƏFTƏ', 'TRAFİK', 'HESAB', 'AVTOMOBİL', 'PLANET', 'DAVRANIŞ', 'MƏTBƏX', 'ŞƏHƏR', 'BƏZƏN',
              'MÜƏYYƏN', 'AYRI', 'QİYMƏT', 'HAQQINDA', 'ÇIXARMAQ', 'QOL', 'YALNIZ', 'HAZIRLAMAQ', 'ŞÜŞƏ', 'NƏHAYƏT', 'YAVAŞ',
              'ZƏRURİ', 'ƏHƏMİYYƏT', 'XATİRƏ', 'YALAN', 'AKTİV', 'SƏNƏT', 'FAİZ', 'DİŞ', 'SATIŞ', 'TƏBİ', 'ÖZ',
              'İQTİSADİ', 'AĞRI', 'YOX', 'QORUMAQ', 'MƏRTƏBƏ', 'İQTİSADİYYAT', 'ÜMUMİ', 'MÜƏYYƏN ', 'FOTO', 'HEYVAN', 'MÜHARİBƏ',
              'MAL', 'SAÇ', 'İTİRMƏK', 'QALIQ', 'DƏYİŞİKLİK', 'DÖRD', 'HƏQİQƏTƏN', 'SƏHİFƏ', 'TEXNOLOGİYA', 'QURUM', 'BEŞ',
              'SEKTOR', 'GENİŞ', 'KAĞIZ', 'ƏTİR', 'SAĞALMAQ', 'İSTİ', 'ƏSR', 'KÜÇƏ', 'BAZAR', 'YUMUŞAQ', 'ETMƏK', 'İSTİFADƏ', 'SİNİF',
              'SEVGİ', 'DOĞULMUŞ', 'AĞIR', 'YENİDƏN', 'GÜNƏŞ', 'SİQARET', 'AĞAC', 'SÖZ', 'BİNA', 'ARVAD', 'QAÇMAQ', 'PARTİYA', 'YATAQ ',
              'MÜƏLLİF', 'QULAQ', 'MÜƏLLİM', 'SƏBƏB', 'SOL', 'YAXŞI', 'YAĞ', 'ÇÜNKİ', 'BAŞA', 'DÜŞMƏK', 'GƏLMƏK', 'GÜLMƏK', 'QAYDA', 'TUTMAQ',
              'SATMAQ', 'ŞEİR', 'GÖNDƏRMƏK', 'UĞUR', 'MÖHKƏM', 'HÖKUMƏT', 'ÜRƏK', 'KƏSMƏK', 'LAYİHƏ', 'LAZIMDIR', 'SÜRƏT', 'İNTİHAR',
              'VUR', 'MODEL', 'BALIQ', 'ŞƏKƏR', 'BAXIŞ', 'BURADA', 'BAL', 'MİQDAR', 'BİRİNCİ', 'KVADRAT', 'ÖLÇÜ',
              'SEÇMƏK', 'TƏTBİQ', 'ETMƏK', 'BAĞ', 'SEVGİ', 'ÇÖRƏK', 'BOYU', 'QAÇMAQ', 'DOLU', 'QURULUŞ', 'DEMƏK', 'QORXU',
              'KÖMƏK', 'GÖRÜŞ', 'ƏŞYALAR', 'GÖZƏlİK', 'İT', 'MƏŞHUR', 'BÖYÜMƏK', 'MƏNALI', 'GƏZMƏK', 'OLDUQCA', 'ÜSTƏLİK',
              'YAŞAMAQ', 'AĞLAMAQ', 'İSTƏMƏK', 'ADAM', 'ÇALIŞMAQ', 'QARDAŞ', 'ÇƏKİLMƏL', 'HARADA', 'OĞURLUQ', 'İCAZƏ', 'QORXU',
              'İŞĞAL', 'MİSAL', 'YALNIZ', 'İZAH', 'FİKİR', 'TEZ', 'PƏNCƏRƏ', 'İŞLƏ', 'DAŞ', 'YANĞIN', 'FƏRQ',
              'KİFAYƏT', 'DOLDURMAQ', 'BƏZİ', 'ŞƏRT', 'QONŞU', 'KİŞİLİK', 'TELEGRAM', 'İSTEHSAL', 'ÜSTÜNDƏ', 'TUTMAQ', 'NAZİK',
              'NEÇƏ', 'ÜMUMİ', 'İNSTAQRAM', 'ŞƏKİL', 'BERİ', 'DƏRS', 'SƏDR', 'QURTULMAQ', 'SAYI', 'DƏFƏ',
              'OLMAQ', 'QƏRB', 'BAŞA', 'DÜŞMƏK', 'HƏR', 'HANSI', 'SİNEMA', 'FƏRQLİ', 'HƏDƏF', 'YUXU', 'DOST', 'FİKİR',
              'ANLAYIŞ', 'USTA', 'MƏTBUAT', 'KƏNAR', 'NƏZARƏT', 'SEÇİM', 'DİN', 'GÜCLÜ', 'HƏLƏ', 'PLAN', 'BEYİN',
              'ELEKTRİK', 'FACEBOOK', 'ŞƏBƏKƏ', 'İÇKİ', 'TƏMİN', 'EDİLMİŞ', 'OXUYAN', 'XƏTT', 'UÇMAQ', 'ÜZV', 'DƏRİ', 'RUH',
              'ƏZİZ', 'YANAŞMA', 'PROSES', 'BAXIŞ', 'ELM', 'İRƏLİ', 'İFADƏ', 'BƏDƏN', 'XATIRLA', 'QƏZA',
              'HƏRTƏRƏFLİ', 'DAĞ', 'YAXIN', 'ADDIM', 'CİDDİ', 'HƏLL', 'İMPRESS', 'YAŞAYIŞ', 'İNKİŞAF', 'SEÇKİ',
              'AĞLAMAQ', 'ƏLAQƏLİ', 'KONSERT', 'ARTIM', 'FƏALİYYƏT', 'ZƏRƏR', 'DƏRİN', 'SALON', 'MÜBARƏK', 'KƏSİLMİŞ',
              'İZLƏMƏK', 'BİRDƏN', 'TUTMAQ', 'SAYMAQ', 'toplamaq', 'ütmək', 'QIŞQIRMAQ', 'MƏSULİYYƏT', 'HƏRƏKƏT', 'DAVA',
              'MƏKTUB', 'SOYUQ', 'CANLI', 'SAXLAMAQ', 'MAŞIN', 'İSTİFADƏ', 'KÖHNƏ', 'BOŞ', 'görəsən', 'DƏRMAN', 'MENECER',
              'QOVMAQ', 'METRE', 'SAXLA', 'KEYFİYYƏT', 'BİTKİ', 'DƏYİŞİKLİK', 'TİBB', 'KREDİT', 'QANUN', 'UĞURLU',
              'BİR', 'imkan', 'cəza', 'hər', 'ŞEY', 'YARDIM', 'TOP', 'EKSPERT', 'DOLDURMA', 'KANAL', 'BOŞLUQ', 'UYĞUN',
              'İLLİK', 'BUNA', 'GÖRƏ', 'YAZMAQ', 'AİD', 'OLMAQ', 'BARMAQ', 'SAYMAQ', 'ATMAQ', 'MÜƏYYƏN', 'ETMƏK', 'NORMAL', 'HELE',
              'PRİNSİP', 'QIRMIZI', 'ROL', 'MAHNI', 'KEYFİYƏTSİZ', 'HAZIR', 'BƏYƏN', 'NƏSƏ', 'MÜƏLLİM', 'OĞLAN', 'GÜNDƏLİK', 'SİYASƏT',
              'CİNAYƏT', 'NİYƏ', 'SƏHNƏ', 'İLİŞMƏK', 'ÖZƏL', 'OTURMAQ', 'SAXLA', 'ARTİST', 'ÜSTÜNLÜK', 'UZAMAQ', 'SƏHNƏ',
              'ƏLAVƏLİ', 'MEŞƏ', 'AYRI', 'SİFARİŞ', 'FAİZ', 'ADƏTƏN', 'HƏMİŞƏ', 'HEKAYƏ', 'KƏLİMƏ', 'ORADAN', 'SİZDƏN',
              'VERGİ', 'RƏY', 'QARDAŞ', 'MƏTBUAT', 'DƏSTƏK', 'GEYİNMƏK', 'SƏHV', 'LİMİT', 'BİRLİK', 'İŞ', 'GÖRÜŞMƏK', 'YARIM', 'YETƏR', 'FƏRDİ', 'QARANLIQ', 'AVTOBUS', 'SANİYƏ', 'KÖRPƏ', 'VƏTƏNDAŞ', 'NAZİR', 'ZAMAN', 'MİLLƏT',
              'REKLAM', 'YÜKSƏLMƏ', 'ÖLÇÜ', 'COLA', 'FANTA', 'SOSİAL', 'KİMSƏ', 'KEÇMİŞ', 'XƏSTƏXANA', 'VARLIQ',
              'GÖRÜŞ', 'JURNALİST', 'DAXİLİ', 'XƏBƏRSIZ', 'KEYFİYYƏT', 'BİTDİ', 'BİTİŞ', 'YERLƏŞİN', 'GİRİŞ', 'RAHAT',
              'CƏMİ', 'BİRLİKDƏ', 'MAĞAZA', 'GİZLİ', 'OXŞAR', 'DƏRİ', 'ÇEVİRMƏK', 'DÖYÜŞ', 'PROBLEM', 'XİDMƏT', 'MÜALİCƏ',
              'YAŞIL', 'NAZİRLİK', 'TƏZYİQ', 'REAKSİYA', 'CÜMLƏ', 'İSTƏK', 'AZADLIQ', 'YENİDƏN', 'ŞƏXSİYYƏT', 'MƏSƏLƏ', 'ÜÇÜNCÜ',
              'MÜƏYYƏN', 'QİYMƏTLƏNDİRMƏK', 'MARAQLI', 'SÜRÜCÜ', 'SÜD', 'TUTMAQ', 'ƏŞYA', 'BEYNƏLXALQ', 'NAMİZƏD',
              'ÇƏKİ', 'MİLYARD', 'SAĞLAM', 'SIXINTI', 'TANRI', 'RƏFTAR', 'SOSİAL', 'NƏŞRİYYAT', 'DİQQƏTLİ', 'SON', 'DƏRƏCƏ',
              'TOPLA', 'İNVESTİSİYA', 'İŞIQLANDIRMAQ', 'QARIŞDIRMAQ', 'TƏHLÜKƏ', 'ZAMAN', 'DAİRƏ', 'İMKAN', 'İNFORMASİYA', 'QARIŞDIRMAQ'
              , 'HEKAYƏ', 'TAMAMİLƏ', 'TƏYYARƏ', 'CAVAB', 'TƏBİƏT', 'EVLƏNMƏK', 'BURUN', 'FAİZ', 'ƏLBƏTTƏ', 'İŞÇİ', 'İŞ',
              'QISACA', 'MAĞAZA', 'MEDİA', 'ÇÜNKİ', 'ARTIM', 'ÇIXARMAQ', 'İCTİMAİ', 'SIĞORTA', 'YAY', 'ÜRƏK', 'SƏNƏD',
              'SƏY', 'HƏR', 'GÜN', 'EKSPRESS', 'RİSK', 'DANIŞMA', 'SÖZ', 'DEMOKRATİYA', 'DUZ', 'MƏSCİD', 'YAŞ', 'AŞAĞI',
              'ƏTRAFINDA', 'TEZLİKLƏ', 'TƏRƏVƏZ', 'ORQAN', 'ÖLDÜRMƏK', 'BAŞQA', 'İL', 'QIRMAQ', 'BAXMAQ', 'MEYVƏ', 'ASMAQ',
              'ŞİRİN', 'AYAQ', 'DƏYİŞİKLİK', 'QANUN', 'KÜLƏK', 'RESPUBLİKA', 'TƏKMİLLƏŞMƏK', 'ÜSTÜN', 'YEDDİ', 'AZALMAQ',
              'QOŞUN', 'MOBİL', 'ÜNSİYYƏT', 'MENECER', 'OTEL', 'QAÇMAQ', 'ZÖVQ', 'SÜRÜŞ', 'TƏHLÜKƏSİZLİK', 'QANUN',
              'ALƏTLƏR', 'TƏHLÜKƏLİ', 'OXUMAQ', 'TÜFƏNG', 'TƏLƏB', 'ULDUZ', 'İNTENSİV', 'ƏSGƏR', 'SADƏ', 'QAZ',
              'TƏTBİQ', 'İSTEHSAL', 'YEMƏK', 'DÜNƏN', 'BAX', 'HAQQINDA', 'ALIŞ', 'ŞÜUR', 'ÇƏRÇİVƏ',
              'LAZIMDIR', 'MÖVCUD', 'UZATMAQ', 'TORT', 'KİNO', 'QOŞULMAQ', 'MƏSƏLƏN', 'DEMƏK', 'SAYT',
              'KÖMƏK', 'BACI', 'ÇİÇƏK', 'HAMISI', 'HÖRMƏT', 'ÖDƏMƏK', 'İSTEDAD', 'AĞIRLIQ', 'AĞIL', 'ÇƏTİN', 'BUNDAN',
              'ÇAY', 'GEDƏR', 'MÜƏYYƏN', 'ZƏNGİN', 'HEÇ', 'SÖZ', 'TƏŞKİLAT', 'TİCARƏT', 'BOYUN', 'cihaz',
              'balans', 'GERİYƏ', 'ÇÜNKİ', 'QƏHVƏ', 'ƏZƏLƏ', 'MONTAJ', 'BAŞQA', 'İŞLƏMƏK', 'ÜNVAN',
              'PAŞA', 'İSTİLİK', 'OK', 'güvən', 'marka', 'yarpaq', 'FAYDA', 'YAYMAQ', 'AXAN', 'ÇƏKMƏK', 'DÜŞÜNMƏK',
              'ÜRƏK', 'ARZU', 'TƏRƏFSİZ', 'ŞƏRAB', 'YUXARI', 'QIZIL', 'ALMAQ', 'TƏMİZ',
              'VİTAMİN', 'ƏLAVƏ', 'GEC', 'AKTYOR', 'YUMURTA', 'HƏRƏKƏT', 'KABAB', 'KƏSMƏ', "BÖHRAN", 'ŞİRNİYYAT',
              'SÖNDÜRMƏK'
             ]


def kelime_sec():
    return random.choice(kelimeler)